export const tags = [
    { label: 'Scrum', value: 'scrum' },
    { label: 'Lógica de Programação', value: 'logica' },
    { label: 'Clean Code', value: 'clean_code' },
    { label: 'Testes de Software', value: 'testes_software' },
    { label: 'Arquitetura de Software', value: 'arquitetura_software' },
    { label: 'Programação Orientada a Objetos', value: 'poo' },
    { label: 'Metodologias Ágeis', value: 'metodologias_ageis' },
    { label: 'Desenvolvimento Frontend', value: 'frontend' },
    { label: 'Desenvolvimento Backend', value: 'backend' },
    { label: 'DevOps', value: 'devops' },
    { label: 'Versionamento de Código (Git)', value: 'git' },
    { label: 'JavaScript', value: 'javascript' },
    { label: 'Python', value: 'python' },
    { label: 'Java', value: 'java' },
    { label: 'C#', value: 'csharp' },
    { label: 'Node.js', value: 'nodejs' },
    { label: 'React', value: 'react' },
    { label: 'Angular', value: 'angular' },
    { label: 'Vue.js', value: 'vuejs' },
    { label: 'Machine Learning', value: 'machine_learning' },
    { label: 'Inteligência Artificial', value: 'inteligencia_artificial' },
    { label: 'Banco de Dados Relacional', value: 'banco_dados_relacional' },
    { label: 'NoSQL', value: 'nosql' },
    { label: 'CI/CD', value: 'cicd' },
    { label: 'Arquitetura de Microsserviços', value: 'microsservicos' },
    { label: 'Programação Funcional', value: 'programacao_funcional' },
    { label: 'API Restful', value: 'api_restful' },
    { label: 'GraphQL', value: 'graphql' },
    { label: 'Test-Driven Development (TDD)', value: 'tdd' },
    { label: 'Continuous Integration', value: 'continuous_integration' },
    { label: 'Docker', value: 'docker' },
    { label: 'Kubernetes', value: 'kubernetes' },
    { label: 'Blockchain', value: 'blockchain' },
    { label: 'Cloud Computing', value: 'cloud_computing' },
    { label: 'Big Data', value: 'big_data' },
    { label: 'Internet das Coisas (IoT)', value: 'iot' },
    { label: 'UI/UX Design', value: 'ui_ux_design' },
    { label: 'Cybersecurity', value: 'cybersecurity' },
    { label: 'Performance de Aplicações', value: 'performance_aplicacoes' },
    { label: 'Desenvolvimento de APIs', value: 'desenvolvimento_apis' },
  ];
